package com.cleardragonf.ourmod.MCM;

import com.google.common.collect.ImmutableMap;
import net.minecraft.item.Item;
import net.minecraft.item.Items;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class MCMValues {

    public Map<Item, Integer> mcmList = new HashMap<>();

    public Map<Item, Integer> Map(){
        mcmList.put(Items.ACACIA_BOAT, 15);
        mcmList.put(Items.ACACIA_BUTTON,12);
        mcmList.put(Items.ACACIA_DOOR, 18);
        mcmList.put(Items.ACACIA_FENCE,15);
        mcmList.put(Items.ACACIA_FENCE_GATE, 15);
        mcmList.put(Items.ACACIA_LOG, 1);
        mcmList.put(Items.ACACIA_PLANKS, 3);
        mcmList.put(Items.ACACIA_PRESSURE_PLATE, 9);
        mcmList.put(Items.ACACIA_SAPLING, 1);
        mcmList.put(Items.ACACIA_SIGN,19);
        mcmList.put(Items.ACACIA_SLAB, 9);
        mcmList.put(Items.ACACIA_STAIRS, 18);
        mcmList.put(Items.ACACIA_TRAPDOOR, 18);
        mcmList.put(Items.ACACIA_WOOD, 1);
        mcmList.put(Items.ACTIVATOR_RAIL, 6070);
        mcmList.put(Items.ANDESITE_SLAB, 3);
        mcmList.put(Items.ANDESITE_STAIRS, 6);
        mcmList.put(Items.ANDESITE_WALL, 6);
        mcmList.put(Items.ANVIL, 31000);
        mcmList.put(Items.APPLE, 128);
        mcmList.put(Items.ARMOR_STAND, 18);
        mcmList.put(Items.ARROW, 54);
        mcmList.put(Items.BAKED_POTATO, 64);
        mcmList.put(Items.BAMBOO,32);
        mcmList.put(Items.BARREL,36);
        mcmList.put(Items.BAT_SPAWN_EGG, 128);
        mcmList.put(Items.BEACON, 139476);
        mcmList.put(Items.BEE_NEST, 128);
        mcmList.put(Items.BEE_SPAWN_EGG, 128);
        mcmList.put(Items.BEEF, 64);
        mcmList.put(Items.BEEHIVE, 128);
        mcmList.put(Items.BEETROOT,64);
        mcmList.put(Items.BEETROOT_SEEDS,16);
        mcmList.put(Items.BEETROOT_SOUP, 73);
        mcmList.put(Items.BIRCH_BOAT,15);
        mcmList.put(Items.BIRCH_BUTTON,12);
        mcmList.put(Items.BIRCH_DOOR,18);
        mcmList.put(Items.BIRCH_FENCE,15);
        mcmList.put(Items.BIRCH_FENCE_GATE,15);
        mcmList.put(Items.BIRCH_LOG, 1);
        mcmList.put(Items.BIRCH_PLANKS,3);
        mcmList.put(Items.BIRCH_PRESSURE_PLATE,9);
        mcmList.put(Items.BIRCH_SAPLING, 1);
        mcmList.put(Items.BIRCH_SIGN,19);
        mcmList.put(Items.BIRCH_SLAB,9);
        mcmList.put(Items.BIRCH_STAIRS,6);
        mcmList.put(Items.BIRCH_TRAPDOOR,18);
        mcmList.put(Items.BIRCH_WOOD,1);
        mcmList.put(Items.BLACK_BANNER,28);
        mcmList.put(Items.BLACK_BED,36);
        mcmList.put(Items.BLACK_CARPET,27);
        mcmList.put(Items.BLACK_CONCRETE, 50);
        mcmList.put(Items.BLACK_CONCRETE_POWDER,25);
        mcmList.put(Items.BLACK_DYE,16);
        mcmList.put(Items.BLACK_SHULKER_BOX,2048);
        mcmList.put(Items.BLACK_STAINED_GLASS,3);
        mcmList.put(Items.BLACK_STAINED_GLASS_PANE,9);
        mcmList.put(Items.BLAZE_POWDER,1536);
        mcmList.put(Items.BLAZE_ROD,1536);
        mcmList.put(Items.BLAZE_SPAWN_EGG,128);
        mcmList.put(Items.BLUE_BANNER,28);
        mcmList.put(Items.BLUE_BED,36);
        mcmList.put(Items.BLUE_CARPET,27);
        mcmList.put(Items.BLUE_CONCRETE,50);
        mcmList.put(Items.BLUE_CONCRETE_POWDER,25);
        mcmList.put(Items.BLUE_DYE,16);
        mcmList.put(Items.BLUE_ICE,6);
        mcmList.put(Items.BLUE_SHULKER_BOX,2048);
        mcmList.put(Items.BLUE_STAINED_GLASS,3);
        mcmList.put(Items.BLUE_STAINED_GLASS_PANE,9);
        mcmList.put(Items.BONE,144);
        mcmList.put(Items.BONE_BLOCK,1296);
        mcmList.put(Items.BONE_MEAL,144);
        mcmList.put(Items.BOOK,15);
        mcmList.put(Items.BOOKSHELF,63);
        mcmList.put(Items.BOW,15);
        mcmList.put(Items.BOWL,9);
        mcmList.put(Items.BREAD,72);
        mcmList.put(Items.BREWING_STAND,1539);
        mcmList.put(Items.BRICK,2);
        mcmList.put(Items.BRICK_SLAB,6 );
        mcmList.put(Items.BRICK_STAIRS,12);
        mcmList.put(Items.BRICK_WALL,12);
        mcmList.put(Items.BRICKS,4);
        mcmList.put(Items.BROWN_BANNER,28);
        mcmList.put(Items.BROWN_BED,36);
        mcmList.put(Items.BROWN_CARPET,27);
        mcmList.put(Items.BROWN_CONCRETE,50);
        mcmList.put(Items.BROWN_CONCRETE_POWDER,25);
        mcmList.put(Items.BROWN_DYE, 16);
        mcmList.put(Items.BROWN_MUSHROOM,32);
        mcmList.put(Items.BROWN_MUSHROOM_BLOCK,288);
        mcmList.put(Items.BROWN_SHULKER_BOX,2048);
        mcmList.put(Items.BROWN_STAINED_GLASS,3);
        mcmList.put(Items.BROWN_STAINED_GLASS_PANE,9);
        mcmList.put(Items.BUCKET,3000);
        mcmList.put(Items.CACTUS,8);
        mcmList.put(Items.CAKE, 126);
        mcmList.put(Items.CAMPFIRE,8);
        mcmList.put(Items.CARROT,64);
        mcmList.put(Items.CARROT_ON_A_STICK,74);
        mcmList.put(Items.CARTOGRAPHY_TABLE,20);
        mcmList.put(Items.CARVED_PUMPKIN,100);
        mcmList.put(Items.CAT_SPAWN_EGG,128);
        mcmList.put(Items.CAULDRON,7000);
        mcmList.put(Items.CAVE_SPIDER_SPAWN_EGG,128);
        mcmList.put(Items.CHARCOAL,1);
        mcmList.put(Items.CHEST,24);
        mcmList.put(Items.CHEST_MINECART,5024);
        mcmList.put(Items.CHICKEN,64);
        mcmList.put(Items.CHICKEN_SPAWN_EGG,128);
        mcmList.put(Items.CHIPPED_ANVIL,15500);
        mcmList.put(Items.CHISELED_QUARTZ_BLOCK,256);
        mcmList.put(Items.CHISELED_RED_SANDSTONE,4);
        mcmList.put(Items.CHISELED_SANDSTONE,4);
        mcmList.put(Items.CHORUS_FLOWER,96);
        mcmList.put(Items.CHORUS_FRUIT,192);
        mcmList.put(Items.CHORUS_PLANT,64);
        mcmList.put(Items.CLAY,16);
        mcmList.put(Items.CLAY_BALL,4);
        mcmList.put(Items.CLOCK,4064);
        mcmList.put(Items.COAL,128);
        mcmList.put(Items.COAL_BLOCK,1152);
        mcmList.put(Items.COAL_ORE,512);
        mcmList.put(Items.COARSE_DIRT,1);
        mcmList.put(Items.COBBLESTONE,1);
        mcmList.put(Items.COBBLESTONE_SLAB,6);
        mcmList.put(Items.COBBLESTONE_STAIRS,6);
        mcmList.put(Items.COBBLESTONE_WALL,6);
        mcmList.put(Items.COBWEB,12);
        mcmList.put(Items.COCOA_BEANS,2);
        mcmList.put(Items.COD,4);
        mcmList.put(Items.COD_BUCKET,4);
        mcmList.put(Items.COD_SPAWN_EGG,128);
        mcmList.put(Items.COMPARATOR,455);
        mcmList.put(Items.COMPASS,4064);
        mcmList.put(Items.COMPOSTER,7);
        mcmList.put(Items.COOKED_BEEF,66);
        mcmList.put(Items.COOKED_CHICKEN,66);
        mcmList.put(Items.COOKED_COD,5);
        mcmList.put(Items.COOKED_MUTTON,66);
        mcmList.put(Items.COOKED_PORKCHOP,66);
        mcmList.put(Items.COOKED_RABBIT,66);
        mcmList.put(Items.COOKED_SALMON,5);
        mcmList.put(Items.COOKIE,50);
        mcmList.put(Items.COW_SPAWN_EGG,128);
        mcmList.put(Items.CRACKED_STONE_BRICKS,1);
        mcmList.put(Items.CRAFTING_TABLE,12);
        mcmList.put(Items.CREEPER_BANNER_PATTERN,28);
        mcmList.put(Items.CREEPER_SPAWN_EGG,128);
        mcmList.put(Items.CROSSBOW,2014);
        mcmList.put(Items.CUT_RED_SANDSTONE,4);
        mcmList.put(Items.CUT_RED_SANDSTONE_SLAB,6);
        mcmList.put(Items.CUT_SANDSTONE,4);
        mcmList.put(Items.CUT_SANDSTONE_SLAB,6);
        mcmList.put(Items.CYAN_BANNER,28);
        mcmList.put(Items.CYAN_BED,36);
        mcmList.put(Items.CYAN_CARPET,27);
        mcmList.put(Items.CYAN_CONCRETE,50);
        mcmList.put(Items.CYAN_CONCRETE_POWDER,25);
        mcmList.put(Items.CYAN_DYE,16);
        mcmList.put(Items.CYAN_SHULKER_BOX,2048);
        mcmList.put(Items.CYAN_STAINED_GLASS,3);
        mcmList.put(Items.CYAN_STAINED_GLASS_PANE,9);
        mcmList.put(Items.DAMAGED_ANVIL,7750);
        mcmList.put(Items.DARK_OAK_BOAT,15);
        mcmList.put(Items.DARK_OAK_BUTTON,12);
        mcmList.put(Items.DARK_OAK_DOOR,18);
        mcmList.put(Items.DARK_OAK_FENCE,15);
        mcmList.put(Items.DARK_OAK_FENCE_GATE,15);
        mcmList.put(Items.DARK_OAK_LOG,1);
        mcmList.put(Items.DARK_OAK_PLANKS,3);
        mcmList.put(Items.DARK_OAK_PRESSURE_PLATE,9);
        mcmList.put(Items.DARK_OAK_SAPLING,1);
        mcmList.put(Items.DARK_OAK_SIGN,19);
        mcmList.put(Items.DARK_OAK_SLAB,9);
        mcmList.put(Items.DARK_OAK_STAIRS,18);
        mcmList.put(Items.DARK_OAK_TRAPDOOR,18);
        mcmList.put(Items.DARK_OAK_WOOD,1);
        mcmList.put(Items.DARK_PRISMARINE,256);
        mcmList.put(Items.DARK_PRISMARINE_SLAB,2304);
        mcmList.put(Items.DARK_PRISMARINE_STAIRS,1536);
        mcmList.put(Items.DAYLIGHT_DETECTOR,272);
        mcmList.put(Items.DETECTOR_RAIL,6065);
        mcmList.put(Items.DIAMOND,8192);
        mcmList.put(Items.DIAMOND_AXE,24582);
        mcmList.put(Items.DIAMOND_BLOCK,73728);
        mcmList.put(Items.DIAMOND_BOOTS,32768);
        mcmList.put(Items.DIAMOND_CHESTPLATE,57344);
        mcmList.put(Items.DIAMOND_HELMET,40960);
        mcmList.put(Items.DIAMOND_HOE,16390);
        mcmList.put(Items.DIAMOND_HORSE_ARMOR,49152);
        mcmList.put(Items.DIAMOND_LEGGINGS,57344);
        mcmList.put(Items.DIAMOND_ORE,24576);
        mcmList.put(Items.DIAMOND_PICKAXE,24582);
        mcmList.put(Items.DIAMOND_SHOVEL,8197);
        mcmList.put(Items.DIAMOND_SWORD,16387);
        mcmList.put(Items.DIORITE_SLAB,3);
        mcmList.put(Items.DIORITE_STAIRS,6);
        mcmList.put(Items.DIORITE_WALL,6);
        mcmList.put(Items.DISPENSER,86);
        mcmList.put(Items.DOLPHIN_SPAWN_EGG,128);
        mcmList.put(Items.DONKEY_SPAWN_EGG,128);
        mcmList.put(Items.DRAGON_BREATH,200000);
        mcmList.put(Items.DRAGON_EGG,2621444);
        mcmList.put(Items.DROPPER,71);
        mcmList.put(Items.DROWNED_SPAWN_EGG,128);
        mcmList.put(Items.EGG,32);
        mcmList.put(Items.ELDER_GUARDIAN_SPAWN_EGG,128);
        mcmList.put(Items.EMERALD,2000);
        mcmList.put(Items.EMERALD_BLOCK,18000);
        mcmList.put(Items.EMERALD_ORE,6000);
        mcmList.put(Items.ENCHANTED_BOOK,2048);
        mcmList.put(Items.ENCHANTED_GOLDEN_APPLE,2048);
        mcmList.put(Items.ENCHANTING_TABLE,16655);
        mcmList.put(Items.END_CRYSTAL,1000);
        mcmList.put(Items.END_PORTAL_FRAME,3000);
        mcmList.put(Items.END_ROD,3000);
        mcmList.put(Items.END_STONE_BRICK_SLAB,3);
        mcmList.put(Items.END_STONE_BRICK_STAIRS,6);
        mcmList.put(Items.END_STONE_BRICK_WALL,6);
        mcmList.put(Items.END_STONE_BRICKS,4);
        mcmList.put(Items.ENDER_CHEST,3072);
        mcmList.put(Items.ENDER_EYE,2560);
        mcmList.put(Items.ENDER_PEARL,1024);
        mcmList.put(Items.ENDERMAN_SPAWN_EGG,128);
        mcmList.put(Items.ENDERMITE_SPAWN_EGG,128);
        mcmList.put(Items.EVOKER_SPAWN_EGG,128);
        mcmList.put(Items.EXPERIENCE_BOTTLE,128);
        mcmList.put(Items.FEATHER,48);
        mcmList.put(Items.FERMENTED_SPIDER_EYE,150);
        mcmList.put(Items.FIRE_CHARGE,50);
        mcmList.put(Items.FISHING_ROD,12);
        mcmList.put(Items.FLETCHING_TABLE,20);
        mcmList.put(Items.FLINT,4);
        mcmList.put(Items.FLINT_AND_STEEL,1004);
        mcmList.put(Items.FLOWER_BANNER_PATTERN,28);
        mcmList.put(Items.FLOWER_POT,6);
        mcmList.put(Items.FOX_SPAWN_EGG,128);
        mcmList.put(Items.FURNACE,8);
        mcmList.put(Items.FURNACE_MINECART,5008);
        mcmList.put(Items.GHAST_SPAWN_EGG,128);
        mcmList.put(Items.GHAST_TEAR,4096);
        mcmList.put(Items.GLASS,4);
        mcmList.put(Items.GLASS_BOTTLE,12);
        mcmList.put(Items.GLASS_PANE,24);
        mcmList.put(Items.GLISTERING_MELON_SLICE,16);
        mcmList.put(Items.GLOBE_BANNER_PATTERN,28);
        mcmList.put(Items.GLOWSTONE,384);
        mcmList.put(Items.GLOWSTONE_DUST,96);
        mcmList.put(Items.GOLD_BLOCK,9000);
        mcmList.put(Items.GOLD_INGOT,1000);
        mcmList.put(Items.GOLD_NUGGET,111);
        mcmList.put(Items.GOLD_ORE,1000);
        mcmList.put(Items.GOLDEN_APPLE,8128);
        mcmList.put(Items.GOLDEN_AXE,3006);
        mcmList.put(Items.GOLDEN_BOOTS,4000);
        mcmList.put(Items.GOLDEN_CARROT,952);
        mcmList.put(Items.GOLDEN_CHESTPLATE,8000);
        mcmList.put(Items.GOLDEN_HELMET,5000);
        mcmList.put(Items.GOLDEN_HOE,2006);
        mcmList.put(Items.GOLDEN_HORSE_ARMOR,6000);
        mcmList.put(Items.GOLDEN_LEGGINGS,7000  );
        mcmList.put(Items.GOLDEN_PICKAXE,3006);
        mcmList.put(Items.GOLDEN_SHOVEL,1006);
        mcmList.put(Items.GOLDEN_SWORD,2003);
        mcmList.put(Items.GRAY_BANNER,28);
        mcmList.put(Items.GRAY_BED,36);
        mcmList.put(Items.GRAY_CARPET,27);
        mcmList.put(Items.GRAY_CONCRETE,50);
        mcmList.put(Items.GRAY_CONCRETE_POWDER,25);
        mcmList.put(Items.GRAY_DYE,16);
        mcmList.put(Items.GRAY_SHULKER_BOX,2048);
        mcmList.put(Items.GRAY_STAINED_GLASS,3);
        mcmList.put(Items.GRAY_STAINED_GLASS_PANE,9);
        mcmList.put(Items.GREEN_BANNER,28);
        mcmList.put(Items.GREEN_BED,36);
        mcmList.put(Items.GREEN_CARPET,27);
        mcmList.put(Items.GREEN_CONCRETE,50);
        mcmList.put(Items.GREEN_CONCRETE_POWDER,25);
        mcmList.put(Items.GREEN_DYE,16);
        mcmList.put(Items.GREEN_SHULKER_BOX,2048);
        mcmList.put(Items.GREEN_STAINED_GLASS,3);
        mcmList.put(Items.GREEN_STAINED_GLASS_PANE,9);
        mcmList.put(Items.GRINDSTONE,10);
        mcmList.put(Items.GUARDIAN_SPAWN_EGG,128);
        mcmList.put(Items.GUNPOWDER,192);
        mcmList.put(Items.HAY_BLOCK,216);
        mcmList.put(Items.HEART_OF_THE_SEA,5000);
        mcmList.put(Items.HEAVY_WEIGHTED_PRESSURE_PLATE,2000);
        mcmList.put(Items.HONEY_BLOCK,4);
        mcmList.put(Items.HONEY_BOTTLE, 52);
        mcmList.put(Items.HONEYCOMB_BLOCK,16);
        mcmList.put(Items.HOPPER,5024);
        mcmList.put(Items.HOPPER_MINECART,10024);
        mcmList.put(Items.HORSE_SPAWN_EGG,128);
        mcmList.put(Items.HUSK_SPAWN_EGG,128);
        mcmList.put(Items.INFESTED_CHISELED_STONE_BRICKS,2);
        mcmList.put(Items.INFESTED_COBBLESTONE,2);
        mcmList.put(Items.INFESTED_MOSSY_STONE_BRICKS,2);
        mcmList.put(Items.INFESTED_CRACKED_STONE_BRICKS,2);
        mcmList.put(Items.INFESTED_STONE,2);
        mcmList.put(Items.INFESTED_STONE_BRICKS,2);
        mcmList.put(Items.INK_SAC,16);
        mcmList.put(Items.IRON_AXE,3006);
        mcmList.put(Items.IRON_BARS,6000);
        mcmList.put(Items.IRON_BLOCK,9000);
        mcmList.put(Items.IRON_BOOTS,4000);
        mcmList.put(Items.IRON_CHESTPLATE,8000);
        mcmList.put(Items.IRON_DOOR,6000);
        mcmList.put(Items.IRON_HELMET,5000);
        mcmList.put(Items.IRON_HOE,2006);
        mcmList.put(Items.IRON_HORSE_ARMOR,6000);
        mcmList.put(Items.IRON_INGOT,1000);
        mcmList.put(Items.IRON_LEGGINGS,7000);
        mcmList.put(Items.IRON_NUGGET,111);
        mcmList.put(Items.IRON_ORE,1000 );
        mcmList.put(Items.IRON_PICKAXE,3006);
        mcmList.put(Items.IRON_SHOVEL,1006);
        mcmList.put(Items.IRON_SWORD,2003);
        mcmList.put(Items.IRON_TRAPDOOR,6000);
        mcmList.put(Items.ITEM_FRAME,15);
        mcmList.put(Items.JUKEBOX,8216);
        mcmList.put(Items.JUNGLE_BOAT,15);
        mcmList.put(Items.JUNGLE_BUTTON,12);
        mcmList.put(Items.JUNGLE_DOOR,18);
        mcmList.put(Items.JUNGLE_FENCE,15);
        mcmList.put(Items.JUNGLE_FENCE_GATE,15);
        mcmList.put(Items.JUNGLE_LOG,1);
        mcmList.put(Items.JUNGLE_PLANKS,3);
        mcmList.put(Items.JUNGLE_PRESSURE_PLATE,6);
        mcmList.put(Items.JUNGLE_SIGN,19);
        mcmList.put(Items.JUNGLE_SLAB,9);
        mcmList.put(Items.JUNGLE_STAIRS,6);
        mcmList.put(Items.JUNGLE_TRAPDOOR,18);
        mcmList.put(Items.JUNGLE_WOOD,1);
        mcmList.put(Items.LADDER,9);
        mcmList.put(Items.LANTERN,1019);
        mcmList.put(Items.LAPIS_BLOCK,27000);
        mcmList.put(Items.LAPIS_LAZULI,3000);
        mcmList.put(Items.LAPIS_ORE,9000);
        mcmList.put(Items.LAVA_BUCKET,3010);
        mcmList.put(Items.LEATHER,3);
        mcmList.put(Items.LEATHER_BOOTS,12);
        mcmList.put(Items.LEATHER_CHESTPLATE,24);
        mcmList.put(Items.LEATHER_HELMET,15);
        mcmList.put(Items.LEATHER_HORSE_ARMOR,18);
        mcmList.put(Items.LEATHER_LEGGINGS,21);
        mcmList.put(Items.LECTERN,99);
        mcmList.put(Items.LEVER,4);
        mcmList.put(Items.LIGHT_BLUE_BANNER,28);
        mcmList.put(Items.LIGHT_BLUE_BED,36);
        mcmList.put(Items.LIGHT_BLUE_CARPET,27);
        mcmList.put(Items.LIGHT_BLUE_CONCRETE,50);
        mcmList.put(Items.LIGHT_BLUE_CONCRETE_POWDER,25);
        mcmList.put(Items.LIGHT_BLUE_DYE,16);
        mcmList.put(Items.LIGHT_BLUE_SHULKER_BOX,2048);
        mcmList.put(Items.LIGHT_BLUE_STAINED_GLASS,3);
        mcmList.put(Items.LIGHT_BLUE_STAINED_GLASS_PANE,9);
        mcmList.put(Items.LIGHT_GRAY_BANNER,28);
        mcmList.put(Items.LIGHT_GRAY_BED,36);
        mcmList.put(Items.LIGHT_GRAY_CARPET,27);
        mcmList.put(Items.LIGHT_GRAY_CONCRETE,50);
        mcmList.put(Items.LIGHT_GRAY_CONCRETE_POWDER,25);
        mcmList.put(Items.LIGHT_GRAY_DYE,16);
        mcmList.put(Items.LIGHT_GRAY_SHULKER_BOX,2048);
        mcmList.put(Items.LIGHT_GRAY_STAINED_GLASS,3);
        mcmList.put(Items.LIGHT_GRAY_STAINED_GLASS_PANE,9);
        mcmList.put(Items.LIGHT_WEIGHTED_PRESSURE_PLATE,9);
        mcmList.put(Items.LIME_BANNER,28);
        mcmList.put(Items.LIME_BED,36);
        mcmList.put(Items.LIME_CARPET,27);
        mcmList.put(Items.LIME_CONCRETE,27);
        mcmList.put(Items.LIME_CONCRETE_POWDER,25);
        mcmList.put(Items.LIME_DYE,16);
        mcmList.put(Items.LIME_SHULKER_BOX,2048);
        mcmList.put(Items.LIME_STAINED_GLASS,3);
        mcmList.put(Items.LIME_STAINED_GLASS_PANE,9);
        mcmList.put(Items.LLAMA_SPAWN_EGG,128);
        mcmList.put(Items.LOOM,9);

        //old list

        mcmList.put(Items.STONE_BRICKS, 1);
        mcmList.put(Items.NETHERRACK, 1);
        mcmList.put(Items.SAND, 1);
        mcmList.put(Items.SNOW, 1);
        mcmList.put(Items.ICE, 1);
        mcmList.put(Items.GRAVEL, 4);
        mcmList.put(Items.VINE, 8);
        mcmList.put(Items.LILY_PAD, 16);
        mcmList.put(Items.RED_MUSHROOM, 32);
        mcmList.put(Items.SOUL_SAND, 49);
        mcmList.put(Items.OBSIDIAN, 64);
        mcmList.put(Items.SPONGE, 128);
        mcmList.put(Items.TALL_GRASS, 1);
        mcmList.put(Items.PACKED_ICE, 4);
        mcmList.put(Items.MAGMA_BLOCK, 128);
        mcmList.put(Items.WHEAT_SEEDS, 16);
        mcmList.put(Items.MELON, 16);
        mcmList.put(Items.WHEAT, 24);
        mcmList.put(Items.NETHER_WART, 24);
        mcmList.put(Items.PUMPKIN, 144);
        mcmList.put(Items.PORKCHOP, 64);
        mcmList.put(Items.RABBIT, 64);
        mcmList.put(Items.MUTTON, 64);
        mcmList.put(Items.TROPICAL_FISH, 64);
        mcmList.put(Items.PUFFERFISH, 64);
        mcmList.put(Items.POTATO, 64);
        mcmList.put(Items.POISONOUS_POTATO, 64);
        mcmList.put(Items.ROTTEN_FLESH, 32);
        mcmList.put(Items.SLIME_BALL, 32);
        mcmList.put(Items.RABBIT_HIDE, 16);
        mcmList.put(Items.RABBIT_FOOT, 128);
        mcmList.put(Items.SPIDER_EYE, 128);
        mcmList.put(Items.GUNPOWDER, 192);
        mcmList.put(Items.SHULKER_SHELL, 2048);
        mcmList.put(Items.GHAST_TEAR, 4096);
        mcmList.put(Items.POTION, 0);
        mcmList.put(Items.SADDLE, 192);
        mcmList.put(Items.NAME_TAG, 192);
        mcmList.put(Items.MUSIC_DISC_11, 2048);
        mcmList.put(Items.MUSIC_DISC_13, 2048);
        mcmList.put(Items.MUSIC_DISC_BLOCKS, 2048);
        mcmList.put(Items.MUSIC_DISC_CAT, 2048);
        mcmList.put(Items.MUSIC_DISC_CHIRP, 2048);
        mcmList.put(Items.MUSIC_DISC_FAR, 2048);
        mcmList.put(Items.MUSIC_DISC_MALL, 2048);
        mcmList.put(Items.MUSIC_DISC_MELLOHI, 2048);
        mcmList.put(Items.MUSIC_DISC_STAL, 2048);
        mcmList.put(Items.MUSIC_DISC_STRAD, 2048);
        mcmList.put(Items.MUSIC_DISC_WAIT, 2048);
        mcmList.put(Items.MUSIC_DISC_WARD, 2048);
        mcmList.put(Items.REDSTONE, 64);
        mcmList.put(Items.GLOWSTONE, 384);
        mcmList.put(Items.QUARTZ, 256);
        mcmList.put(Items.PRISMARINE, 256);
        mcmList.put(Items.PRISMARINE_CRYSTALS, 512);
        mcmList.put(Items.NETHER_STAR, 139264);
        mcmList.put(Items.SNOWBALL, 1);
        mcmList.put(Items.IRON_INGOT, 1000);
        mcmList.put(Items.LAPIS_LAZULI, 1000);
        mcmList.put(Items.LAPIS_ORE, 3000);
        mcmList.put(Items.LAPIS_BLOCK, 9000);
        return mcmList;
    }

    public Map<Item, Integer> getMap(){
        return Map();
    }
}


